"""Add IssueFix and update ModelStat

Revision ID: 542e1639b760
Revises: 8b5ae97df38b
Create Date: 2026-04-06 21:22:01.995180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542e1639b760'
down_revision = '8b5ae97df38b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_fixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('issue_title', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('FOUND', 'VERIFIED', 'FIXED', 'FAILED', name='vulnerabilitystatus'), nullable=True),
    sa.Column('pr_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_fixes_id'), 'issue_fixes', ['id'], unique=False)
    op.add_column('model_stats', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_stats', 'provider')
    op.drop_index(op.f('ix_issue_fixes_id'), table_name='issue_fixes')
    op.drop_table('issue_fixes')
    # ### end Alembic commands ###
