"""Add terminal_logs table for clickable UI history

Revision ID: de73a4c81fd9
Revises: 542e1639b760
Create Date: 2026-04-06 22:12:55.655122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de73a4c81fd9'
down_revision = '542e1639b760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_logs_bot_id'), 'terminal_logs', ['bot_id'], unique=False)
    op.create_index(op.f('ix_terminal_logs_id'), 'terminal_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terminal_logs_id'), table_name='terminal_logs')
    op.drop_index(op.f('ix_terminal_logs_bot_id'), table_name='terminal_logs')
    op.drop_table('terminal_logs')
    # ### end Alembic commands ###
